import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';

/**
 * Generate a TXT file for image descriptions
 */
export async function generateDescriptionFile(
  filename: string,
  description: string,
  confidence: number,
  source: string,
  timestamp: Date
): Promise<string> {
  const content = `Image Description
================

Filename: ${filename}
Description: ${description}
Generated: ${timestamp.toLocaleString()}

---
Generated by AutoWithAI
`;

  // Save to public/downloads directory
  const downloadsDir = join(process.cwd(), 'public', 'downloads', 'descriptions');
  await mkdir(downloadsDir, { recursive: true });
  
  const fileName = `${filename.replace(/\.[^/.]+$/, '')}_${Date.now()}_description.txt`;
  const filePath = join(downloadsDir, fileName);
  
  await writeFile(filePath, content, 'utf-8');
  
  // Return public URL
  return `/downloads/descriptions/${fileName}`;
}

/**
 * Generate a CSV file for metadata
 */
export async function generateMetadataCSV(
  filename: string,
  title: string,
  keywords: string,
  category: string,
  timestamp: Date
): Promise<string> {
  // CSV format with proper escaping
  const escapeCSV = (str: string) => {
    if (str.includes(',') || str.includes('"') || str.includes('\n')) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };

  const content = `Filename,Title,Keywords,Category
${escapeCSV(filename)},${escapeCSV(title)},${escapeCSV(keywords)},${escapeCSV(category)}
`;

  // Save to public/downloads directory
  const downloadsDir = join(process.cwd(), 'public', 'downloads', 'metadata');
  await mkdir(downloadsDir, { recursive: true });
  
  const fileName = `${filename.replace(/\.[^/.]+$/, '')}_${Date.now()}_metadata.csv`;
  const filePath = join(downloadsDir, fileName);
  
  await writeFile(filePath, content, 'utf-8');
  
  // Return public URL
  return `/downloads/metadata/${fileName}`;
}

/**
 * Generate a TXT file for runway prompts (single image - not used for batch)
 */
export async function generateRunwayPromptsFile(
  filename: string,
  mode: string,
  lowMotion?: string,
  mediumMotion?: string,
  highMotion?: string,
  timestamp?: Date
): Promise<string> {
  let content = `Runway Prompts
==============

Filename: ${filename}

`;

  if (lowMotion) {
    content += `Low Motion Prompt:
${lowMotion}

`;
  }

  if (mediumMotion) {
    content += `Medium Motion Prompt:
${mediumMotion}

`;
  }

  if (highMotion) {
    content += `High Motion Prompt:
${highMotion}

`;
  }

  content += `---
Generated by AutoWithAI
`;

  // Save to public/downloads directory
  const downloadsDir = join(process.cwd(), 'public', 'downloads', 'runway-prompts');
  await mkdir(downloadsDir, { recursive: true });
  
  const fileName = `${filename.replace(/\.[^/.]+$/, '')}_${Date.now()}_runway.txt`;
  const filePath = join(downloadsDir, fileName);
  
  await writeFile(filePath, content, 'utf-8');
  
  // Return public URL
  return `/downloads/runway-prompts/${fileName}`;
}

/**
 * Generate bulk descriptions TXT file (for batch processing)
 */
export async function generateBulkDescriptionsFile(
  descriptions: Array<{
    filename: string;
    description: string;
    confidence: number;
    source: string;
  }>,
  timestamp: Date
): Promise<string> {
  let content = `Image Descriptions - Batch Processing
======================================

Total Images: ${descriptions.length}

${'='.repeat(80)}

`;

  descriptions.forEach((item, index) => {
    content += `[${index + 1}] ${item.filename}
${'-'.repeat(80)}
${item.description}

`;
  });

  content += `${'='.repeat(80)}

Generated by AutoWithAI
`;

  // Save to public/downloads directory
  const downloadsDir = join(process.cwd(), 'public', 'downloads', 'descriptions');
  await mkdir(downloadsDir, { recursive: true });
  
  const fileName = `descriptions_batch_${timestamp.toISOString().split('T')[0]}_${timestamp.getTime()}.txt`;
  const filePath = join(downloadsDir, fileName);
  
  await writeFile(filePath, content, 'utf-8');
  
  // Return public URL
  return `/downloads/descriptions/${fileName}`;
}

/**
 * Generate bulk metadata CSV file (for batch processing)
 */
export async function generateBulkMetadataCSV(
  metadata: Array<{
    filename: string;
    title: string;
    keywords: string;
    category: string;
  }>,
  timestamp: Date
): Promise<string> {
  const escapeCSV = (str: string) => {
    if (str.includes(',') || str.includes('"') || str.includes('\n')) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };

  let content = `Filename,Title,Keywords,Category\n`;

  metadata.forEach((item) => {
    content += `${escapeCSV(item.filename)},${escapeCSV(item.title)},${escapeCSV(
      item.keywords
    )},${escapeCSV(item.category)}\n`;
  });

  // Save to public/downloads directory
  const downloadsDir = join(process.cwd(), 'public', 'downloads', 'metadata');
  await mkdir(downloadsDir, { recursive: true });
  
  const fileName = `metadata_batch_${timestamp.toISOString().split('T')[0]}_${timestamp.getTime()}.csv`;
  const filePath = join(downloadsDir, fileName);
  
  await writeFile(filePath, content, 'utf-8');
  
  // Return public URL
  return `/downloads/metadata/${fileName}`;
}

/**
 * Generate bulk runway prompts TXT file (for batch processing)
 */
export async function generateBulkRunwayPromptsFile(
  prompts: Array<{
    filename: string;
    lowMotion?: string;
    mediumMotion?: string;
    highMotion?: string;
  }>,
  timestamp: Date
): Promise<string> {
  let content = `Runway Prompts - Batch Processing
==================================

Total Images: ${prompts.length}

${'='.repeat(80)}

`;

  prompts.forEach((item, index) => {
    content += `[${index + 1}] ${item.filename}
${'-'.repeat(80)}
`;

    if (item.lowMotion) {
      content += `Low Motion:
${item.lowMotion}

`;
    }

    if (item.mediumMotion) {
      content += `Medium Motion:
${item.mediumMotion}

`;
    }

    if (item.highMotion) {
      content += `High Motion:
${item.highMotion}

`;
    }

    content += '\n';
  });

  content += `${'='.repeat(80)}

Generated by AutoWithAI
`;

  // Save to public/downloads directory
  const downloadsDir = join(process.cwd(), 'public', 'downloads', 'runway-prompts');
  await mkdir(downloadsDir, { recursive: true });
  
  const fileName = `runway_prompts_batch_${timestamp.toISOString().split('T')[0]}_${timestamp.getTime()}.txt`;
  const filePath = join(downloadsDir, fileName);
  
  await writeFile(filePath, content, 'utf-8');
  
  // Return public URL
  return `/downloads/runway-prompts/${fileName}`;
}
